/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package painBasico2D;

import SM.AML.IU.Formas;
import SM.AML.IU.Lienzo2D;
import java.awt.Point;
import java.awt.geom.Point2D;

/**
 *
 * @author AntonioML
 */
public class VentanaInterna extends javax.swing.JInternalFrame {
    VentanaPrincipal parent=null;
    /**
     * Creates new form VentanaInterna
     */
    
    
    public Lienzo2D getLienzo2D()
    {
        return this.lienzo2D;
    }
    public VentanaInterna(VentanaPrincipal parent) {
        initComponents();
        this.parent=parent;
    }
    //..
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo2D = new SM.AML.IU.Lienzo2D();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        lienzo2D.setAutoscrolls(true);
        lienzo2D.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzo2DMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout lienzo2DLayout = new javax.swing.GroupLayout(lienzo2D);
        lienzo2D.setLayout(lienzo2DLayout);
        lienzo2DLayout.setHorizontalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        lienzo2DLayout.setVerticalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo2D, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
 //     parent.RefrescarVentanaPrinciapl();
    }//GEN-LAST:event_formMouseEntered

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
         parent.RefrescarVentanaPrinciapl();
    }//GEN-LAST:event_formInternalFrameActivated

    private void lienzo2DMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DMouseMoved
        Point2D punto_lienzo=lienzo2D.ObtenerPosicion();
        Formas forma=lienzo2D.getForma();
        switch(forma)
        {
            case Punto:
                parent.getHerramientaActual().setText("Punto || Cordendas: " + punto_lienzo.toString().substring(15,punto_lienzo.toString().length() ) );
                break;
            case Linea:
                parent.getHerramientaActual().setText("Linea || Cordendas: " + punto_lienzo.toString().substring(15,punto_lienzo.toString().length() ) );
                break;
            case Rectangulo:
                parent.getHerramientaActual().setText("Rectangulo || Cordendas: " + punto_lienzo.toString().substring(15,punto_lienzo.toString().length() ) );
                break;
            case Elipse:
                parent.getHerramientaActual().setText("Elipse || Cordendas: " + punto_lienzo.toString().substring(15,punto_lienzo.toString().length() ) );
                break;
            default:
                parent.getHerramientaActual().setText("Nada seleccionado ");
            
        }
       
    }//GEN-LAST:event_lienzo2DMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SM.AML.IU.Lienzo2D lienzo2D;
    // End of variables declaration//GEN-END:variables
}
