package painBasico2D;

import SM.AML.IU.Formas;
import SM.AML.IU.Lienzo2D;
import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaPrincipal.java
 *
 * Created on 22-mar-2019, 15:49:09
 */
/**
 *
 * @author AntonioML
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    VentanaInterna vi;
    public JLabel getHerramientaActual(){
        return HerramientaActual;
    }
    /** Creates new form VentanaPrincipal */
    public VentanaPrincipal() {
        initComponents();
        this.setSize(400,400);
        vi=new VentanaInterna(this); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConjuntoHerramietas = new javax.swing.ButtonGroup();
        BarraHerramientas = new javax.swing.JToolBar();
        Punto = new javax.swing.JToggleButton();
        Linea = new javax.swing.JToggleButton();
        Rectangulo = new javax.swing.JToggleButton();
        Elipse = new javax.swing.JToggleButton();
        PanelCentral = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        PanelInferior = new javax.swing.JPanel();
        Grosor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TamanioGrosor = new javax.swing.JSpinner();
        Colores = new javax.swing.JPanel();
        botonNegro = new javax.swing.JButton();
        botonRojo = new javax.swing.JButton();
        botonAzul = new javax.swing.JButton();
        botonBlanco = new javax.swing.JButton();
        botonAmarillo = new javax.swing.JButton();
        botonVerde = new javax.swing.JButton();
        Propiedades = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Transparencia = new javax.swing.JCheckBox();
        Relleno = new javax.swing.JCheckBox();
        Alisar = new javax.swing.JCheckBox();
        Editar = new javax.swing.JCheckBox();
        BarraEstado = new javax.swing.JPanel();
        HerramientaActual = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Nuevo = new javax.swing.JMenuItem();
        Abrir = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();
        Edicion = new javax.swing.JMenu();
        VerBarraEstado = new javax.swing.JCheckBoxMenuItem();
        VerFormas = new javax.swing.JCheckBoxMenuItem();
        VerAtributos = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paint Basico 2D");

        BarraHerramientas.setRollover(true);
        BarraHerramientas.setMaximumSize(new java.awt.Dimension(129, 31));
        BarraHerramientas.setMinimumSize(new java.awt.Dimension(129, 31));

        ConjuntoHerramietas.add(Punto);
        Punto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/punto.png"))); // NOI18N
        Punto.setFocusable(false);
        Punto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Punto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuntoActionPerformed(evt);
            }
        });
        BarraHerramientas.add(Punto);

        ConjuntoHerramietas.add(Linea);
        Linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/linea.png"))); // NOI18N
        Linea.setFocusable(false);
        Linea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Linea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineaActionPerformed(evt);
            }
        });
        BarraHerramientas.add(Linea);

        ConjuntoHerramietas.add(Rectangulo);
        Rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rectangulo.png"))); // NOI18N
        Rectangulo.setFocusable(false);
        Rectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Rectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Rectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RectanguloActionPerformed(evt);
            }
        });
        BarraHerramientas.add(Rectangulo);

        ConjuntoHerramietas.add(Elipse);
        Elipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/elipse.png"))); // NOI18N
        Elipse.setFocusable(false);
        Elipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Elipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Elipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElipseActionPerformed(evt);
            }
        });
        BarraHerramientas.add(Elipse);

        getContentPane().add(BarraHerramientas, java.awt.BorderLayout.PAGE_START);

        PanelCentral.setFocusTraversalPolicyProvider(true);
        PanelCentral.setLayout(new java.awt.BorderLayout());

        escritorio.setBackground(new java.awt.Color(240, 240, 240));
        escritorio.setForeground(new java.awt.Color(204, 204, 204));
        escritorio.setLayout(new javax.swing.BoxLayout(escritorio, javax.swing.BoxLayout.LINE_AXIS));
        PanelCentral.add(escritorio, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelCentral, java.awt.BorderLayout.CENTER);

        PanelInferior.setInheritsPopupMenu(true);
        PanelInferior.setLayout(new java.awt.BorderLayout(2, 2));

        Grosor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Grosor.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Grosor");
        Grosor.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        TamanioGrosor.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        TamanioGrosor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TamanioGrosor.setMaximumSize(new java.awt.Dimension(255, 255));
        TamanioGrosor.setOpaque(false);
        TamanioGrosor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                GrosorCambiado(evt);
            }
        });
        Grosor.add(TamanioGrosor, java.awt.BorderLayout.EAST);

        PanelInferior.add(Grosor, java.awt.BorderLayout.CENTER);

        Colores.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Colores.setPreferredSize(new java.awt.Dimension(100, 50));
        Colores.setLayout(new java.awt.GridLayout(2, 0));

        botonNegro.setBackground(java.awt.Color.black);
        botonNegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNegroNegroActivado(evt);
            }
        });
        Colores.add(botonNegro);

        botonRojo.setBackground(java.awt.Color.red);
        botonRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRojorojoActivado(evt);
            }
        });
        Colores.add(botonRojo);

        botonAzul.setBackground(java.awt.Color.blue);
        botonAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAzulazulActivado(evt);
            }
        });
        Colores.add(botonAzul);

        botonBlanco.setBackground(java.awt.Color.white);
        botonBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBlancoblancoActivado(evt);
            }
        });
        Colores.add(botonBlanco);

        botonAmarillo.setBackground(java.awt.Color.yellow);
        botonAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAmarilloamarilloActivado(evt);
            }
        });
        Colores.add(botonAmarillo);

        botonVerde.setBackground(java.awt.Color.green);
        botonVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerdeActionPerformed(evt);
            }
        });
        Colores.add(botonVerde);

        PanelInferior.add(Colores, java.awt.BorderLayout.LINE_START);

        Propiedades.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Propiedades.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Atributos");
        Propiedades.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        Transparencia.setText("Transparencia");
        Transparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransparenciaActionPerformed(evt);
            }
        });
        Propiedades.add(Transparencia, java.awt.BorderLayout.LINE_START);

        Relleno.setText("Relleno");
        Relleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RellenoActionPerformed(evt);
            }
        });
        Propiedades.add(Relleno, java.awt.BorderLayout.EAST);

        Alisar.setText("Alisar");
        Alisar.setAlignmentX(0.5F);
        Alisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlisarActionPerformed(evt);
            }
        });
        Propiedades.add(Alisar, java.awt.BorderLayout.CENTER);

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        Propiedades.add(Editar, java.awt.BorderLayout.SOUTH);

        PanelInferior.add(Propiedades, java.awt.BorderLayout.LINE_END);

        BarraEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BarraEstado.setToolTipText("BarraEstado");
        BarraEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BarraEstado.setMinimumSize(new java.awt.Dimension(83, 20));
        BarraEstado.setLayout(new java.awt.BorderLayout());

        HerramientaActual.setText("Elemento seleccionado");
        BarraEstado.add(HerramientaActual, java.awt.BorderLayout.CENTER);

        PanelInferior.add(BarraEstado, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(PanelInferior, java.awt.BorderLayout.PAGE_END);

        Archivo.setText("Archivo");

        Nuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nuevo.png"))); // NOI18N
        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        Archivo.add(Nuevo);

        Abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        Abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/abrir.png"))); // NOI18N
        Abrir.setText("Abrir");
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        Archivo.add(Abrir);

        Guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/guardar.png"))); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        Archivo.add(Guardar);

        Menu.add(Archivo);

        Edicion.setText("Edicion");

        VerBarraEstado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        VerBarraEstado.setSelected(true);
        VerBarraEstado.setText("Ver barra estado");
        VerBarraEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerBarraEstadoActionPerformed(evt);
            }
        });
        Edicion.add(VerBarraEstado);

        VerFormas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        VerFormas.setSelected(true);
        VerFormas.setText("Ver forma de formas");
        VerFormas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerFormasActionPerformed(evt);
            }
        });
        Edicion.add(VerFormas);

        VerAtributos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        VerAtributos.setSelected(true);
        VerAtributos.setText("Ver barra atributos");
        VerAtributos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerAtributosActionPerformed(evt);
            }
        });
        Edicion.add(VerAtributos);

        Menu.add(Edicion);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RellenoActionPerformed
         vi = (VentanaInterna)escritorio.getSelectedFrame();
        if(Relleno.isSelected())
         {
            vi.getLienzo2D().setRelleno(true);
         }
        else
              vi.getLienzo2D().setRelleno(false);
    }//GEN-LAST:event_RellenoActionPerformed

    private void AlisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlisarActionPerformed
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        if(Alisar.isSelected())
         {
            vi.getLienzo2D().setAlisar(true);
         }
        else
            vi.getLienzo2D().setAlisar(false);
    }//GEN-LAST:event_AlisarActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        vi=new VentanaInterna(this); 
        escritorio.add(vi);
        vi.setVisible(true);
    }//GEN-LAST:event_NuevoActionPerformed

    private void VerBarraEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerBarraEstadoActionPerformed
      boolean verBarra = VerBarraEstado.isSelected();
      BarraEstado.setVisible(verBarra);
    }//GEN-LAST:event_VerBarraEstadoActionPerformed

    private void botonNegroNegroActivado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNegroNegroActivado
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        vi.getLienzo2D().setColor(Color.black);
    }//GEN-LAST:event_botonNegroNegroActivado

    private void botonRojorojoActivado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRojorojoActivado
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        vi.getLienzo2D().setColor(Color.red);
    }//GEN-LAST:event_botonRojorojoActivado

    private void botonAzulazulActivado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAzulazulActivado
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        vi.getLienzo2D().setColor(Color.blue);
    }//GEN-LAST:event_botonAzulazulActivado

    private void botonBlancoblancoActivado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBlancoblancoActivado
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        vi.getLienzo2D().setColor(Color.white);
    }//GEN-LAST:event_botonBlancoblancoActivado

    private void botonAmarilloamarilloActivado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAmarilloamarilloActivado
       VentanaInterna vi=new VentanaInterna(this) ; 
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        vi.getLienzo2D().setColor(Color.yellow);
    }//GEN-LAST:event_botonAmarilloamarilloActivado

    private void botonVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerdeActionPerformed
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        vi.getLienzo2D().setColor(Color.green);
    }//GEN-LAST:event_botonVerdeActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
       vi = (VentanaInterna)escritorio.getSelectedFrame();
       if(Editar.isSelected())
       {
        vi.getLienzo2D().setEditar(true);
       }
       else
        vi.getLienzo2D().setEditar(false);       
    }//GEN-LAST:event_EditarActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
        }
    }//GEN-LAST:event_AbrirActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void VerFormasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerFormasActionPerformed
        boolean verFormas = VerFormas.isSelected();
        BarraHerramientas.setVisible(verFormas);
    }//GEN-LAST:event_VerFormasActionPerformed

    private void VerAtributosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerAtributosActionPerformed
        boolean verAtributos = VerAtributos.isSelected();
        Propiedades.setVisible(verAtributos);
    }//GEN-LAST:event_VerAtributosActionPerformed

    private void TransparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransparenciaActionPerformed
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        if(Transparencia.isSelected())
        {
            vi.getLienzo2D().setTranparencia(true);
        }
        else
            vi.getLienzo2D().setTranparencia(false);
    }//GEN-LAST:event_TransparenciaActionPerformed

    private void ElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElipseActionPerformed
       HerramientaActual.setText("Elipse");
       vi = (VentanaInterna)escritorio.getSelectedFrame();
       vi.getLienzo2D().setForma(Formas.Elipse );
    }//GEN-LAST:event_ElipseActionPerformed

    private void RectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RectanguloActionPerformed
        HerramientaActual.setText("Linea");
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        vi.getLienzo2D().setForma(Formas.Rectangulo );
    }//GEN-LAST:event_RectanguloActionPerformed

    private void LineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineaActionPerformed
        HerramientaActual.setText("Linea");
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        vi.getLienzo2D().setForma(Formas.Linea );
    }//GEN-LAST:event_LineaActionPerformed

    private void PuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuntoActionPerformed
        HerramientaActual.setText("Punto");
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        vi.getLienzo2D().setForma(Formas.Punto);
    }//GEN-LAST:event_PuntoActionPerformed

    private void GrosorCambiado(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_GrosorCambiado
       vi = (VentanaInterna)escritorio.getSelectedFrame();
       vi.getLienzo2D().setGrosor((Integer )TamanioGrosor.getValue());
    }//GEN-LAST:event_GrosorCambiado
    //Devoler ventana seleccionada
    public VentanaInterna VentanaSeleccionada(){
       vi = (VentanaInterna)escritorio.getSelectedFrame();
       return vi;
    }
    
    public void RefrescarVentanaPrinciapl(){
        vi = (VentanaInterna)escritorio.getSelectedFrame();
        Lienzo2D lienzo_actual=vi.getLienzo2D();
        Alisar.setSelected(lienzo_actual.getAlisar());
        Editar.setSelected(lienzo_actual.getEditar());
        Relleno.setSelected(lienzo_actual.getRelleno());
        Transparencia.setSelected(lienzo_actual.getTransparencia()); 
        TamanioGrosor.setValue(lienzo_actual.getGrosor());
        
        switch(lienzo_actual.getForma()){
            case Punto:
                Punto.setSelected(true);
                break;
            case Linea:
                Linea.setSelected(true);
                break;
            case Rectangulo:
                Rectangulo.setSelected(true);
                break;
            case Elipse:
                Elipse.setSelected(true);
                break;
        }
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JCheckBox Alisar;
    private javax.swing.JMenu Archivo;
    private javax.swing.JPanel BarraEstado;
    private javax.swing.JToolBar BarraHerramientas;
    private javax.swing.JPanel Colores;
    private javax.swing.ButtonGroup ConjuntoHerramietas;
    private javax.swing.JMenu Edicion;
    private javax.swing.JCheckBox Editar;
    private javax.swing.JToggleButton Elipse;
    private javax.swing.JPanel Grosor;
    private javax.swing.JMenuItem Guardar;
    private javax.swing.JLabel HerramientaActual;
    private javax.swing.JToggleButton Linea;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem Nuevo;
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JPanel PanelInferior;
    private javax.swing.JPanel Propiedades;
    private javax.swing.JToggleButton Punto;
    private javax.swing.JToggleButton Rectangulo;
    private javax.swing.JCheckBox Relleno;
    private javax.swing.JSpinner TamanioGrosor;
    private javax.swing.JCheckBox Transparencia;
    private javax.swing.JCheckBoxMenuItem VerAtributos;
    private javax.swing.JCheckBoxMenuItem VerBarraEstado;
    private javax.swing.JCheckBoxMenuItem VerFormas;
    private javax.swing.JButton botonAmarillo;
    private javax.swing.JButton botonAzul;
    private javax.swing.JButton botonBlanco;
    private javax.swing.JButton botonNegro;
    private javax.swing.JButton botonRojo;
    private javax.swing.JButton botonVerde;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
